name: Update GitHub Profile Stats

on:
  schedule:
    - cron: "0 0 * * *"   # daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          username: nupurmirani
          show_icons: true
          theme: tokyonight
          output: assets/stats.svg

      - name: Generate Top Languages
        uses: anuraghazra/github-readme-stats@master
        with:
          username: nupurmirani
          layout: compact
          theme: tokyonight
          output: assets/languages.svg

      - name: Commit files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add assets
          git commit -m "update profile stats" || exit 0
          git push
